// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace TransCare.Data.Configurations
{
    public partial class ProviderConfiguration : IEntityTypeConfiguration<Provider>
    {
        public void Configure(EntityTypeBuilder<Provider> entity)
        {
            entity.ToTable("Provider");

            entity.Property(e => e.City)
                .IsRequired()
                .HasMaxLength(35)
                .IsUnicode(false);

            entity.Property(e => e.Latitude)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasDefaultValueSql("((0))");

            entity.Property(e => e.Longitude)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasDefaultValueSql("((0))");

            entity.Property(e => e.Notes).IsUnicode(false);

            entity.Property(e => e.Phone)
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.Property(e => e.ProviderName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.State)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false);

            entity.Property(e => e.Street)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);

            entity.Property(e => e.Url)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.ZipCode)
                .IsRequired()
                .HasMaxLength(5)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Provider> entity);
    }
}
