name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |   
        cd /home/runner/work/TransCare/TransCare/src/TransCare.Web
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release -o ./trans-care-app -r win-x64 -f net6.0 --self-contained true 
    
    #- name: Test
      #run: dotnet test --no-build --verbosity normal
    
    - name: Variable Substitution
      uses: microsoft/variable-substitution@v1 
      with:
          files: '**/appsettings.json'
      env:
          ConnectionStrings.TransCareDatabase: ${{ secrets.SQL_CONNECTION_STRING }}
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: trans-care-artifact
        path: ./trans-care-app
        
    - name: FTP Deployer
      uses: sand4rt/ftp-deployer@v1.3
      with:
        sftp: false # optional
        host: ${{ secrets.FTP_SERVER }} # e.g. ftp.host.com or sftp.host.com (without ftp:// or ftps://)
        port: 21 # optional, default is: 21
        username: ${{ secrets.FTP_USERNAME }} # FTP username
        password: ${{ secrets.FTP_PASSWORD }} # FTP password
        remote_folder: ${{ secrets.FTP_REMOTE_FOLDER }} # optional, remote path of your FTP server
        local_folder: ./trans-care-app # optional, local path, default is: dist
        cleanup: true # optional, remove existing files inside FTP remote folder
        # include: [] # optional, e.g. ['dist']
        # exclude: [] # optional, e.g. ['node_modules/**', '.git/**', '*.env']
        pasive: true # optional    
        
