#name: .NET
name: "TransCare"

on:
  push:
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'README.md'
    
jobs: 

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: |   
        cd ../../TransCare/TransCare/src/TransCare.Web
        dotnet publish "TransCare.Web.csproj" -c Release -o "../../trans-care-app" -r win-x64 -f net6.0 --self-contained true 
      
    - name: Variable Substitution
      uses: microsoft/variable-substitution@v1 
      with:
          files: '**/appsettings.json'
      env:
          ConnectionStrings.TransCareDatabase: ${{ secrets.SQL_CONNECTION_STRING }}
          ApiKeys.GoogleMaps: ${{ secrets.API_KEY_GOOGLE_MAPS }}
           
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./trans-care-app/
        server-dir: ${{ secrets.FTP_REMOTE_PATH }}/
        dangerous-clean-slate: true
        log-level: standard
    
        
        
