#name: .NET
name: "TransCare"

on:
  push:
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'README.md'
    
jobs: 

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: |   
        cd ../../TransCare/TransCare/src/TransCare.Web
        dotnet publish "TransCare.Web.csproj" -c Release -o "../../trans-care-app" -r win-x64 -f net6.0 --self-contained true 
      
    - name: Variable Substitution
      uses: microsoft/variable-substitution@v1 
      with:
          files: '**/appsettings.json'
      env:
          ConnectionStrings.TransCareDatabase: ${{ secrets.SQL_CONNECTION_STRING }}
          ApiKeys.GoogleMaps: ${{ secrets.API_KEY_GOOGLE_MAPS }}
          
    - name: Stop site offline by renaimg _app_offline.htm
      shell: python
      run: |
        import ftplib
        ftp = ftplib.FTP('${{ secrets.FTP_SERVER }}')
        ftp.login('${{ secrets.FTP_USERNAME }}', '${{ secrets.FTP_PASSWORD }}')        
        ftp.rename('_app_offline.htm', 'app_offline.htm')
        ftp.quit()
           
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        exclude: app_offline.htm
        local-dir: ./trans-care-app/
        log-level: standard
        
    - name: Start site by renaming app_offline.htm
      shell: python
      run: |
        import ftplib
        ftp = ftplib.FTP('${{ secrets.FTP_SERVER }}')
        ftp.login('${{ secrets.FTP_USERNAME }}', '${{ secrets.FTP_PASSWORD }}')
        ftp.rename('app_offline.htm', '_app_offline.htm')
        ftp.quit()
    
        
        
